# Generated by Django 6.0.3 on 2026-03-12 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('danger', 'Nguy hiểm')], default='warning', max_length=10)),
                ('alert_type', models.CharField(choices=[('air', 'Chất lượng không khí'), ('uhi', 'Nhiệt đô thị'), ('water', 'Chất lượng nước'), ('flood', 'Ngập úng'), ('ndvi', 'Thảm thực vật'), ('other', 'Khác')], default='air', max_length=10)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
