# Generated by Django 6.0.3 on 2026-03-13 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0002_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('air', 'Chất lượng không khí'), ('water', 'Chất lượng nước'), ('noise', 'Tiếng ồn'), ('waste', 'Rác thải'), ('green', 'Cây xanh'), ('other', 'Khác')], default='other', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('district', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewing', 'Đang xem xét'), ('resolved', 'Đã xử lý')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
