# Generated by Django 6.0.3 on 2026-03-31 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0003_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=200, verbose_name='Khu vực')),
                ('alert_type', models.CharField(blank=True, max_length=50)),
                ('problem_type', models.CharField(choices=[('aqi', 'Ô nhiễm không khí'), ('uhi', 'Đảo nhiệt đô thị'), ('ndvi', 'Thiếu cây xanh'), ('combined', 'Kết hợp nhiều yếu tố')], default='combined', max_length=20)),
                ('solution', models.TextField(verbose_name='Giải pháp đề xuất')),
                ('evidence', models.TextField(blank=True, verbose_name='Cơ sở khoa học')),
                ('status', models.CharField(choices=[('pending', 'Chờ xét duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Phản hồi admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đề xuất giải pháp',
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
