# Generated by Django 6.0.3 on 2026-04-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0004_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản Trị Viên'), ('researcher', 'Nhà Nghiên Cứu'), ('viewer', 'Người Xem')], default='viewer', max_length=20),
        ),
    ]
